Vagrant.configure("2") do |config|
		config.vm.define "rundeck" do |rundeck|
			rundeck.vm.box = "centos/7"
			rundeck.vm.network "public_network", bridged: "Realtek Gaming GBE Family Controller", ip: "192.168.1.204"
			rundeck.vm.provision "shell", inline: <<-SHELL
						sudo echo "rundeck" > /etc/hostname && \						
						sudo yum update -y && \
						sudo yum install -y epel-release ; yum update -y && \
						sudo yum install -y wget perl iotop net-tools htop nfs-utils git java-1.8.0 && \
						sudo rpm -Uvh https://repo.rundeck.org/latest.rpm && sudo yum install -y rundeck && \
						sudo sed -i "s/localhost:4440/192.168.1.204:4440/g" /etc/rundeck/rundeck-config.properties && \            
						sudo service rundeckd start && \
						sudo service firewalld stop && systemctl disable firewalld && \
						sudo setenforce 0 && sudo reboot					
						SHELL
					config.vm.provider "virtualbox" do |v|
						v.memory = "512"
						v.cpus = "4"
						v.name = "rundeck"
					end
			end
end