Vagrant.configure("2") do |config|
		config.vm.define "guacamole" do |config|
			config.vm.box = "centos/7"
			config.vm.network "public_network", bridge: "enp3s0", ip: "192.168.1.230"
			config.vm.provision "shell", path: "./script.sh"
					config.vm.provider "hyperv" do |h|
						h.memory = "1024"
						h.cpus = "2"
						h.vmname = "Guacamole"
					end
		end
end