Vagrant.configure("2") do |config|
		config.vm.define "zabbix-4.4" do |config|
			config.vm.box = "centos/7"
			config.vm.network "public_network", auto_config: false
			config.vm.provision "shell", path: "./script.sh"
					config.vm.provider "virtualbox" do |v|
						v.memory = "1024"
						v.cpus = "2"
						v.name = "zabbix-4.4"
					end
			end
end