Vagrant.configure("2") do |config|
		config.vm.define "alexandria" do |config|
			config.vm.box = "centos/7"
			config.vm.network "public_network", bridge: "Realtek Gaming GBE Family Controller"
			config.vm.provision "shell", path: "./script01.sh" 
			config.vm.provision :reload
			config.vm.provision "shell", path: "./script02.sh" 
			config.vm.provision :reload
					config.vm.provider "virtualbox" do |v|
						v.memory = "1024"
						v.cpus = "4"
						v.name = "alexandria"
					end
			end
end