Vagrant.configure("2") do |config|
	#(1..2).each do |i| 
		config.vm.define "zabbix_agent01" do |config|
			config.vm.box = "centos/7"
			config.vm.network "public_network"
			config.vm.provision "shell", path: "./script01.sh"
					config.vm.provider "virtualbox" do |v|
						v.memory = "512"
						v.cpus = "2"
						v.name = "zabbix_agent01"
					end
			end
	#end
end