Vagrant.configure("2") do |config|
		config.vm.define "Beterraba" do |config|
			config.vm.box = "centos/7"
			config.vm.network "public_network"
			config.vm.provision "shell", path: "./script.sh"
			config.vm.provision :reload
					config.vm.provider "virtualbox" do |v|
						v.memory = "512"
						v.cpus = "2"
						v.name = "Beterraba"
					end
			end
end