Vagrant.configure("2") do |config|
		config.vm.define "madlab" do |config|
			config.vm.box = "centos/8"
			config.vm.network "public_network", auto_config: false
			#config.vm.provision "shell", path: "./script02.sh"
					config.vm.provider "virtualbox" do |v|
						v.memory = "1024"
						v.cpus = "2"
						v.name = "madlab"
					end
			end
end