Vagrant.configure("2") do |config|
		config.vm.define "nxfilter" do |config|
			config.vm.box = "centos/7"
			config.vm.network "public_network", auto_config: false
			#config.vm.provision "shell", path: "./script02.sh"
					config.vm.provider "virtualbox" do |v|
						v.memory = "3096"
						v.cpus = "4"
						v.name = "nxfilter"
					end
			end
end