Vagrant.configure("2") do |config|
	(1..3).each do |i| 
		config.vm.define "robot0#{i}" do |config|
			config.vm.box = "centos/7"
			config.vm.network "public_network", bridge: "enp3s0"
			config.vm.provision "shell", path: "./script0#{i}.sh"
			config.vm.provision :reload
					config.vm.provider "virtualbox" do |v|
						v.memory = "2048"
						v.cpus = "2"
						v.name = "robot0#{i}"
					end
		end
	end
end          